import React from 'react';

// Shared data — properties, rooms, blog posts.

const PROPERTIES = [
  { id: "maris", city: "Cap-Ferrat", country: "France", climate: "Mediterranean", climateColor: "#0875FF", description: "Limestone, sea breeze.", lat: 60, lng: 56 },
  { id: "verde", city: "Engadin Valley", country: "Switzerland", climate: "Alpine", climateColor: "#7047EB", description: "Forest spa, fireplaces.", lat: 28, lng: 50 },
  { id: "brondo", city: "Lisbon", country: "Portugal", climate: "Coastal", climateColor: "#FF4D3E", description: "Tile, terracotta, hills.", lat: 70, lng: 18 },
  { id: "noor", city: "Marrakech", country: "Morocco", climate: "Desert", climateColor: "#FFC233", description: "Riad calm, courtyards.", lat: 80, lng: 28 },
  { id: "haven", city: "Kyoto", country: "Japan", climate: "Temperate", climateColor: "#64B450", description: "Wood, paper, gardens.", lat: 18, lng: 82 },
  { id: "marina", city: "Tulum", country: "Mexico", climate: "Tropical", climateColor: "#0875FF", description: "Reef, palms, candlelight.", lat: 88, lng: 80 },
];

const ROOMS = [
  {
    id: "maris-suite",
    title: "Cliffside Sea Suite",
    location: "Otel Maris · Cap-Ferrat",
    property: "maris",
    type: "Suite",
    image: "assets/room-1.png",
    gallery: ["assets/room-1.png", "assets/about-room.jpg", "assets/hero-room.jpg", "assets/room-2.png"],
    price: 480,
    rating: 5,
    people: 2,
    bed: "King",
    area: 62,
    badge: "Editor's Pick",
    description: "Limestone walls open onto a private terrace cantilevered over the Mediterranean. Linen drapes, a deep soaking tub, and a quiet you can hear.",
    amenities: ["wifi", "pool", "spa", "concierge", "dining", "parking"],
  },
  {
    id: "verde-cabin",
    title: "Forest Cabin Retreat",
    location: "Otel Verde · Engadin",
    property: "verde",
    type: "Cabin",
    image: "assets/room-2.png",
    gallery: ["assets/room-2.png", "assets/hero-room.jpg", "assets/about-room.jpg", "assets/room-3.png"],
    price: 320,
    rating: 5,
    people: 4,
    bed: "King + Twin",
    area: 78,
    badge: "Wellness",
    description: "A timber cabin built into pine and granite. Fireplace, copper bath, and direct access to the spa pavilions.",
    amenities: ["wifi", "spa", "dining", "gym", "concierge", "parking"],
  },
  {
    id: "brondo-loft",
    title: "Architect's Loft",
    location: "Otel Brondo · Lisbon",
    property: "brondo",
    type: "Loft",
    image: "assets/room-3.png",
    gallery: ["assets/room-3.png", "assets/about-room.jpg", "assets/hero-room.jpg", "assets/room-1.png"],
    price: 280,
    rating: 4,
    people: 3,
    bed: "Queen",
    area: 54,
    badge: "City",
    description: "An azulejo-tiled loft above the Bairro Alto, with a steel-framed kitchen and a roof terrace looking over the Tejo.",
    amenities: ["wifi", "dining", "gym", "concierge"],
  },
  {
    id: "noor-courtyard",
    title: "Riad Courtyard Room",
    location: "Otel Noor · Marrakech",
    property: "noor",
    type: "Room",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1400&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1400&q=80",
      "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1400&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1400&q=80",
    ],
    price: 220,
    rating: 5,
    people: 2,
    bed: "Queen",
    area: 42,
    badge: "Garden",
    description: "Hand-cut zellige and a private cedar door onto the orange-tree courtyard. Mint tea served at dusk.",
    amenities: ["wifi", "pool", "spa", "dining", "concierge"],
  },
  {
    id: "haven-tatami",
    title: "Tatami Garden Room",
    location: "Otel Haven · Kyoto",
    property: "haven",
    type: "Room",
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1400&q=80",
      "https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f?w=1400&q=80",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1400&q=80",
      "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1400&q=80",
    ],
    price: 360,
    rating: 5,
    people: 2,
    bed: "Futon",
    area: 38,
    badge: "Heritage",
    description: "Cedar beams, shoji screens, and a private moss garden. An onsen-style bath of hinoki wood.",
    amenities: ["wifi", "spa", "dining", "concierge"],
  },
  {
    id: "marina-bungalow",
    title: "Reef Bungalow",
    location: "Otel Marina · Tulum",
    property: "marina",
    type: "Bungalow",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=900&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1400&q=80",
      "https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?w=1400&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1400&q=80",
    ],
    price: 540,
    rating: 5,
    people: 2,
    bed: "King",
    area: 70,
    badge: "Beachfront",
    description: "Palm-thatched roof, an outdoor shower, and a hammock strung over the sand. Coral-reef snorkelling, two minutes' walk.",
    amenities: ["wifi", "pool", "spa", "dining", "concierge", "parking"],
  },
];

const POSTS = [
  {
    id: "quiet-seasons",
    cat: "Travel Notes",
    date: "Apr 14",
    title: "On the quiet seasons in Cap-Ferrat",
    excerpt: "When the cypress turn gold and the coast empties — our favourite week of the year.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1400&q=80",
    readTime: 6,
  },
  {
    id: "alpine-supper",
    cat: "Dining",
    date: "Mar 28",
    title: "An alpine supper, served by candlelight",
    excerpt: "Chef Léa Vorel on fondue de comté and the case for a long table.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1400&q=80",
    readTime: 4,
  },
  {
    id: "kyoto-mornings",
    cat: "Field Guide",
    date: "Mar 12",
    title: "Six early mornings in Kyoto",
    excerpt: "A walking guide through Higashiyama before the city wakes.",
    image: "https://images.unsplash.com/photo-1545569310-d04c19a7e3e6?w=1400&q=80",
    readTime: 8,
  },
  {
    id: "tulum-reef",
    cat: "Sustainability",
    date: "Feb 22",
    title: "Reef restoration at Otel Marina",
    excerpt: "How a small Tulum lagoon partnership is rebuilding the reef.",
    image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200&q=80",
    readTime: 5,
  },
  {
    id: "marrakech-mint",
    cat: "Culture",
    date: "Feb 04",
    title: "The proper pour of Moroccan mint tea",
    excerpt: "Notes from our concierge in Marrakech, on the ritual and the stretch.",
    image: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=1200&q=80",
    readTime: 3,
  },
];

window.OtelData = { PROPERTIES, ROOMS, POSTS };
